import { C } from "@/lib/constants";
import type { CSSProperties } from "react";

// Shared inline-style tokens used across pages.
export const s = {
  app: {
    minHeight: "100vh",
    background: C.bg,
    color: C.text,
    fontFamily: "'Inter', sans-serif",
  } as CSSProperties,
  nav: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "12px 24px",
    borderBottom: `1px solid ${C.border}`,
    background: C.bg,
    position: "sticky",
    top: 0,
    zIndex: 100,
  } as CSSProperties,
  navBtn: (active: boolean): CSSProperties => ({
    background: active ? C.purpleDim : "transparent",
    border: active ? `1px solid ${C.purple}` : "1px solid transparent",
    color: active ? C.purpleLight : C.textMuted,
    padding: "6px 16px",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    textDecoration: "none",
    display: "inline-block",
  }),
  logo: {
    fontSize: 16,
    fontWeight: 700,
    color: C.purpleLight,
    marginRight: 16,
    letterSpacing: "0.05em",
  } as CSSProperties,
  main: (ai: boolean): CSSProperties => ({
    padding: "24px",
    maxWidth: 1100,
    margin: "0 auto",
    paddingRight: ai ? 360 : 24,
  }),
  sectionTitle: { fontSize: 18, fontWeight: 600, color: C.purpleLight, marginBottom: 14 } as CSSProperties,
  pill: (bg: string, tx: string): CSSProperties => ({
    background: bg,
    color: tx,
    fontSize: 10,
    padding: "2px 8px",
    borderRadius: 99,
    fontWeight: 600,
    display: "inline-block",
  }),
  smallBtn: (color: string): CSSProperties => ({
    background: color + "18",
    color,
    border: `1px solid ${color}44`,
    borderRadius: 6,
    padding: "3px 10px",
    fontSize: 10,
    cursor: "pointer",
  }),
  fab: {
    position: "fixed",
    bottom: 28,
    right: 28,
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: C.purple,
    color: "#fff",
    fontSize: 24,
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: `0 4px 20px ${C.purple}66`,
    zIndex: 200,
  } as CSSProperties,
  modal: {
    position: "fixed",
    inset: 0,
    background: "#000b",
    zIndex: 300,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } as CSSProperties,
  modalBox: (w?: number): CSSProperties => ({
    background: "#1a1a28",
    border: `1px solid ${C.borderLight}`,
    borderRadius: 16,
    padding: 28,
    width: w || 380,
    maxWidth: "95vw",
    maxHeight: "90vh",
    overflowY: "auto",
  }),
  modalTitle: { fontSize: 16, fontWeight: 600, color: C.purpleLight, marginBottom: 18 } as CSSProperties,
  inp: {
    width: "100%",
    background: "#0f0f18",
    border: `1px solid ${C.borderLight}`,
    borderRadius: 8,
    color: C.text,
    padding: "8px 12px",
    fontSize: 13,
    marginBottom: 10,
    boxSizing: "border-box",
  } as CSSProperties,
  ta: {
    width: "100%",
    background: "#0f0f18",
    border: `1px solid ${C.borderLight}`,
    borderRadius: 8,
    color: C.text,
    padding: "8px 12px",
    fontSize: 13,
    marginBottom: 10,
    boxSizing: "border-box",
    resize: "vertical",
    minHeight: 72,
  } as CSSProperties,
  sel: {
    width: "100%",
    background: "#0f0f18",
    border: `1px solid ${C.borderLight}`,
    borderRadius: 8,
    color: C.text,
    padding: "8px 12px",
    fontSize: 13,
    marginBottom: 10,
    boxSizing: "border-box",
  } as CSSProperties,
  btnP: {
    background: C.purple,
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "9px 20px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
  } as CSSProperties,
  btnS: {
    background: "transparent",
    color: C.textMuted,
    border: `1px solid ${C.borderLight}`,
    borderRadius: 8,
    padding: "9px 20px",
    fontSize: 13,
    cursor: "pointer",
    width: "100%",
    marginBottom: 8,
  } as CSSProperties,
  tabBtn: (active: boolean, color: string): CSSProperties => ({
    background: active ? color + "22" : "transparent",
    border: active ? `1px solid ${color}66` : `1px solid ${C.border}`,
    color: active ? color : C.textMuted,
    padding: "6px 14px",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: active ? 600 : 400,
  }),
  // White chat panel
  aiPanel: {
    position: "fixed",
    right: 0,
    top: 0,
    bottom: 0,
    width: 340,
    background: C.chatBg,
    borderLeft: `1px solid ${C.chatBorder}`,
    zIndex: 250,
    display: "flex",
    flexDirection: "column",
  } as CSSProperties,
  aiHeader: {
    padding: "14px 16px",
    borderBottom: `1px solid ${C.chatBorder}`,
    background: C.chatBg,
    display: "flex",
    alignItems: "center",
    gap: 8,
  } as CSSProperties,
  aiMsgUser: {
    background: C.purple,
    color: "#fff",
    borderRadius: "16px 16px 4px 16px",
    padding: "9px 13px",
    fontSize: 13,
    alignSelf: "flex-end",
    maxWidth: "82%",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
  } as CSSProperties,
  aiMsgBot: {
    background: C.chatSurface,
    color: C.chatText,
    border: `1px solid ${C.chatBorder}`,
    borderRadius: "16px 16px 16px 4px",
    padding: "9px 13px",
    fontSize: 13,
    alignSelf: "flex-start",
    maxWidth: "82%",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
  } as CSSProperties,
  aiInputRow: {
    display: "flex",
    gap: 8,
    padding: 12,
    borderTop: `1px solid ${C.chatBorder}`,
    background: C.chatBg,
  } as CSSProperties,
  aiInp: {
    flex: 1,
    background: C.chatSurface,
    border: `1px solid ${C.chatBorder}`,
    borderRadius: 20,
    color: C.chatText,
    padding: "9px 14px",
    fontSize: 13,
    outline: "none",
  } as CSSProperties,
  aiSend: {
    background: C.purple,
    color: "#fff",
    border: "none",
    borderRadius: "50%",
    width: 36,
    height: 36,
    cursor: "pointer",
    fontSize: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } as CSSProperties,
};
