/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as NotenRouteImport } from './routes/noten'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlausurenIndexRouteImport } from './routes/klausuren.index'
import { Route as KlausurenIdRouteImport } from './routes/klausuren.$id'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotenRoute = NotenRouteImport.update({
  id: '/noten',
  path: '/noten',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlausurenIndexRoute = KlausurenIndexRouteImport.update({
  id: '/klausuren/',
  path: '/klausuren/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlausurenIdRoute = KlausurenIdRouteImport.update({
  id: '/klausuren/$id',
  path: '/klausuren/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noten': typeof NotenRoute
  '/todos': typeof TodosRoute
  '/klausuren/$id': typeof KlausurenIdRoute
  '/klausuren/': typeof KlausurenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/noten': typeof NotenRoute
  '/todos': typeof TodosRoute
  '/klausuren/$id': typeof KlausurenIdRoute
  '/klausuren': typeof KlausurenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/noten': typeof NotenRoute
  '/todos': typeof TodosRoute
  '/klausuren/$id': typeof KlausurenIdRoute
  '/klausuren/': typeof KlausurenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/noten' | '/todos' | '/klausuren/$id' | '/klausuren/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/noten' | '/todos' | '/klausuren/$id' | '/klausuren'
  id: '__root__' | '/' | '/noten' | '/todos' | '/klausuren/$id' | '/klausuren/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotenRoute: typeof NotenRoute
  TodosRoute: typeof TodosRoute
  KlausurenIdRoute: typeof KlausurenIdRoute
  KlausurenIndexRoute: typeof KlausurenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noten': {
      id: '/noten'
      path: '/noten'
      fullPath: '/noten'
      preLoaderRoute: typeof NotenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klausuren/': {
      id: '/klausuren/'
      path: '/klausuren'
      fullPath: '/klausuren/'
      preLoaderRoute: typeof KlausurenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klausuren/$id': {
      id: '/klausuren/$id'
      path: '/klausuren/$id'
      fullPath: '/klausuren/$id'
      preLoaderRoute: typeof KlausurenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotenRoute: NotenRoute,
  TodosRoute: TodosRoute,
  KlausurenIdRoute: KlausurenIdRoute,
  KlausurenIndexRoute: KlausurenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
